/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homestock;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;

import java.io.File;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JOptionPane;

/**
 *
 * @author Supaluk Jaroensuk
 */
public class Add_stocks extends javax.swing.JFrame {
    private String itemcode;
    private String itemstocks;
    /**
     * Creates new form Add_stocks
     */
    public Add_stocks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addStock = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backIcon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        searchCode = new javax.swing.JTextField();
        addStock1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addStock.setFont(new java.awt.Font("Heiti SC", 0, 18)); // NOI18N
        addStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addStockKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Heiti SC", 1, 24)); // NOI18N
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Heiti SC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("ITEM CODE");

        backIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/BackIcon.png"))); // NOI18N
        backIcon.setBorder(null);
        backIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backIconActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Heiti SC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("STOCKS");

        searchCode.setFont(new java.awt.Font("Heiti SC", 0, 18)); // NOI18N

        addStock1.setFont(new java.awt.Font("Heiti SC", 1, 24)); // NOI18N
        addStock1.setForeground(new java.awt.Color(153, 153, 153));
        addStock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/TotalItemsIcon.png"))); // NOI18N
        addStock1.setText("Add stocks");
        addStock1.setBorder(null);
        addStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStock1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStock, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(backIcon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(addStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(addStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addStock, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(backIcon)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        itemcode = searchCode.getText();
        itemstocks = addStock.getText();
        
        if(itemcode == null || itemstocks == null){
            JOptionPane.showMessageDialog(null , "Incomplete information");
            new Add_stocks().setVisible(true);
            this.dispose(); 
        }
        
        int stocks = Integer.parseInt(itemstocks);
        
        String save;
        
        String convert = "";
        int quantity;
        
        if(itemcode == null || itemstocks == null){
            JOptionPane.showMessageDialog(null , "Incomplete information");
            new Add_stocks().setVisible(true);
            this.dispose();

        }else{

            String FILE_ITEMS = "src/data/ItemsStock.txt";
            try{
             File file = new File(FILE_ITEMS);
             BufferedReader reader = new BufferedReader(new FileReader(file));
            
             String line = "", oldtext = "",find = "",old = "";
             while((line = reader.readLine()) != null){
                    
                        String[] str = line.split("/");
                        
                        if(str[0].equals(itemcode)){
                            old = str[0] + "/" + str[1] + "/" + str[2] + "/" + str[3] + "/" + str[4];
                            quantity = Integer.parseInt(str[4]);
                            quantity += stocks;
                            
                            convert = String.valueOf(quantity);

                            find =  line.replace(str[3]+"/"+str[4], str[3]+"/"+convert);
                        }
                
                 oldtext += line + "\r\n";
                 
             }
             reader.close();
             // replace a word in a file
             
             //To replace a line in a file
             String newtext = oldtext.replaceAll(old, find);
            
             FileWriter writer = new FileWriter(FILE_ITEMS);
             writer.write(newtext);writer.close();
            
         }
            
         catch (IOException ioe){
             ioe.printStackTrace();
         }
            
        new ITEMS_ADMIN().setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backIconActionPerformed
        new ITEMS_ADMIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backIconActionPerformed

    private void addStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStock1ActionPerformed

    }//GEN-LAST:event_addStock1ActionPerformed

    private void addStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addStockKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                    itemcode = searchCode.getText();
        itemstocks = addStock.getText();
        
        if(itemcode == null || itemstocks == null){
            JOptionPane.showMessageDialog(null , "Incomplete information");
            new Add_stocks().setVisible(true);
            this.dispose(); 
        }
        
        int stocks = Integer.parseInt(itemstocks);
        
        String save;
        
        String convert = "";
        int quantity;
        int count = 0;
        
        if(itemcode == null || itemstocks == null){
            JOptionPane.showMessageDialog(null , "Incomplete information");
            new Add_stocks().setVisible(true);
            this.dispose();

        }else{
            

            String FILE_ITEMS = "src/data/ItemsStock.txt";
            try{
             File file = new File(FILE_ITEMS);
             BufferedReader reader = new BufferedReader(new FileReader(file));
            
             String line = "", oldtext = "",find = "",old = "";
             while((line = reader.readLine()) != null){
                    if(count !=  0 ){
                        String[] str = line.split("/");
                        
                        if(str[0].equals(itemcode)){
                            old = str[0] + "/" + str[1] + "/" + str[2] + "/" + str[3] + "/" + str[4];

                            quantity = Integer.parseInt(str[4]);
                            quantity += stocks;
                            convert = String.valueOf(quantity);
                            find =  line.replace(str[3]+"/"+str[4], str[3]+"/"+convert);
                        }
                }
                 oldtext += line + "\r\n";
                 count++;
             }
             reader.close();
             // replace a word in a file
             
             //To replace a line in a file
             String newtext = oldtext.replaceAll(old, find);
            
             FileWriter writer = new FileWriter(FILE_ITEMS);
             writer.write(newtext);writer.close();
            
         }
            
         catch (IOException ioe){
             ioe.printStackTrace();
         }
            
        new ITEMS_ADMIN().setVisible(true);
        this.dispose();
        }
        }
    }//GEN-LAST:event_addStockKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_stocks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addStock;
    private javax.swing.JButton addStock1;
    private javax.swing.JButton backIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField searchCode;
    // End of variables declaration//GEN-END:variables
}
